
# defaults 定义“默认要加载的其他配置文件”以及加载顺序，- key: value 表示字典项
# - _self_ 表示加载当前配置文件
# - task: Ant 表示加载 cfg/task/Ant.yaml 配置文件
# - train: ${task}PPO 表示加载 cfg/train/AntPPO.yaml 配置文件
# - hydra/job_logging: disabled 表示禁用 hydra 的日志记录功能
# - override hydra/launcher: local 表示使用本地 launcher 启动子进程，而非当前进程
# - override hydra/output: local 表示将输出保存到本地
defaults:
  - _self_
  - task: Ant
  - train: ${task}PPO
  - hydra/job_logging: disabled
  - override hydra/launcher: local
  - override hydra/output: local

# Task name - used to pick the class to load
task_name: ${task.name}
# experiment name. defaults to name of training config
experiment: ''

# env_path for custom environment
env_path: ''

# if set to positive integer, overrides the default number of environments
num_envs: ''

# seed - set to -1 to choose random seed
seed: 42
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: True

collect: True
# used to set checkpoint path
checkpoint: ''
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu horovod training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: ${train.params.config.name}

wandb_entity: 'jma2020'
wandb_project: 'isaac_gpt'
wandb_tags: []
wandb_logcode_dir: '' 

capture_video: False
capture_video_freq: 5000
capture_video_len: 200
force_render: False

headless: True 


